### ISSUE TITLE
Error while packing images

### ISSUE THREAD

**Issue by sven-nm** [brobertson/lacebuilder#4]
* Lacebuilder version: 0.1.2 ? Installed with pip
* Python version: 3.7.10
* Operating System: Linux/Ubuntu 20.04

### Description

Hi Bruce, 
got this error while simply trying to pack two test images. Any hint ? 

### What I Did

```
(lace) najem@sysadmin-Precision-Tower-5810:~/lacebuilder_test$ lacebuilder --outputdir out/ --metadatafile mets.xml packimages  --imagedir img/
outputdir: out/
metadata file: <_io.TextIOWrapper name='mets.xml' mode='r' encoding='UTF-8'>
generating image xar archive
⠋ Binarizing and compressing imagesraised exception trying to read:  <class 'ValueError'>
Traceback (most recent call last):
  File "/home/najem/anaconda3/envs/lace/bin/lacebuilder", line 8, in <module>
    sys.exit(main())
  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/lacebuilder/cli.py", line 37, in packImages
    generate_image_xar(imagedir, outputdir, metadatafile.name, verbose, clobber)
  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/lacebuilder/lacebuilder.py", line 59, in generate_image_xar
    binarize_skimage(input_image_file, fileout_path, verbose)
  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/lacebuilder/lacebuilder.py", line 407, in binarize_skimage
    thresh = threshold_otsu(image)
UnboundLocalError: local variable 'image' referenced before assignment
```

**Comment by brobertson** [comment]
can I have your images? I think there's something wrog in the binarization.

On Mar 23, 2021 7:34 PM, sven-nm ***@***.***> wrote:

  *   Lacebuilder version: 0.1.2 ? Installed with pip
  *   Python version: 3.7.10
  *   Operating System: Linux/Ubuntu 20.04

Description

Hi Bruce,
got this error while simply trying to pack two test images. Any hint ?

What I Did

(lace) ***@***.***Precision-Tower-5810:~/lacebuilder_test$ lacebuilder --outputdir out/ --metadatafile mets.xml packimages  --imagedir img/

outputdir: out/

metadata file: <_io.TextIOWrapper name='mets.xml' mode='r' encoding='UTF-8'>

generating image xar archive

⠋ Binarizing and compressing imagesraised exception trying to read:  <class 'ValueError'>

Traceback (most recent call last):

  File "/home/najem/anaconda3/envs/lace/bin/lacebuilder", line 8, in <module>

    sys.exit(main())

  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/click/core.py", line 829, in __call__

    return self.main(*args, **kwargs)

  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/click/core.py", line 782, in main

    rv = self.invoke(ctx)

  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/click/core.py", line 1289, in invoke

    rv.append(sub_ctx.command.invoke(sub_ctx))

  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/click/core.py", line 1066, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/click/core.py", line 610, in invoke

    return callback(*args, **kwargs)

  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func

    return f(get_current_context(), *args, **kwargs)

  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/lacebuilder/cli.py", line 37, in packImages

    generate_image_xar(imagedir, outputdir, metadatafile.name, verbose, clobber)

  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/lacebuilder/lacebuilder.py", line 59, in generate_image_xar

    binarize_skimage(input_image_file, fileout_path, verbose)

  File "/home/najem/anaconda3/envs/lace/lib/python3.7/site-packages/lacebuilder/lacebuilder.py", line 407, in binarize_skimage

    thresh = threshold_otsu(image)

UnboundLocalError: local variable 'image' referenced before assignment

**Comment by sven-nm** [comment]
Hello Bruce, 

Sorry for the late response. I can't copy the images here because of their .tif format. They'll be in your mailbox in a few minutes :)
